User process survey
Polar-Eclipse/survey-site pull request #36
Opened 2021-07-29 06:29 UTC by wenxi0504

Logged-in user is able to see/edit/delete only their own surveys

2021-07-29 17:39 UTC, JameeKim requested changes
Thanks for the work! Please check the comments below.

In addition to individual comments below, I also need to mention that you need to add the check in `processEditSurveyPage` function, too. Try using [`Survey.findOneAndUpdate`](https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndUpdate).

```ts
Survey.findOneAndUpdate({ owner: userId, _id: id }, updatedSurvey, {}, (err) => {
    if (err) {
        return next(err);
    }
    res.redirect("/account");
    // Same as one of the comments below, this redirects the user regardless of
    // whether the survey with the given id and owner id was found or not.
    // Not a big deal in our case, but ideally, we would want to return an error
    // if no such survey was found.
});
```

2021-07-29 17:39 UTC, JameeKim commented on server/controllers/survey.ts
> +        getSurveyById(id, (err,survey) => {
You are making a `find` call on the database twice to get the same object. We do not want this to minimize database calls. I would suggest using `getSurveyById` only (and get rid of the `Survey.find` call above) and then checking if the `userId` is the same as the `owner` field of the survey object.

```ts
getSurveyById(id, (err, survey) => {
    if (err) {
        return next(err);
    }

    if (!userId.equals(survey.owner)) {
        return res.redirect("/account"); // redirect to the account page
        // OR you could also try sending out 401 Unauthorized error (more advanced)
    }

    // Now you can render the page here
});
```

2021-07-29 17:39 UTC, JameeKim commented on server/controllers/survey.ts
> +        Survey.findByIdAndRemove(id, {}, (err) => {
Same as above, you're requesting 2 database operations. What you want to use is this: [`Survey.findOneAndRemove`](https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndRemove).

```ts
Survey.findOneAndRemove({ owner: userId, _id: id }, (err) => {
    if (err) {
        return next(err);
    }

    res.redirect("/account");
    // This is done regardless of if the survey was actually found with the given id and owner id.
    // In business applications, you might want to do separate things depending on that.
    // In our case, I think it's fine to leave it like this.
});
```

2021-07-29 17:42 UTC, wenxi0504 commented
Message received..I will fix it in the afternoon... Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jamee Kim ***@***.***>
Sent: Thursday, July 29, 2021 1:39:48 PM
To: Polar-Eclipse/survey-site ***@***.***>
Cc: Wen Xu ***@***.***>; Author ***@***.***>
Subject: Re: [Polar-Eclipse/survey-site] User process survey (#36)


@JameeKim requested changes on this pull request.

Thanks for the work! Please check the comments below.

In addition to individual comments below, I also need to mention that you need to add the check in processEditSurveyPage function, too. Try using Survey.findOneAndUpdate<https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndUpdate>.

Survey.findOneAndUpdate({ owner: userId, _id: id }, updatedSurvey, {}, (err) => {
    if (err) {
        return next(err);
    }
    res.redirect("/account");
    // Same as one of the comments below, this redirects the user regardless of
    // whether the survey with the given id and owner id was found or not.
    // Not a big deal in our case, but ideally, we would want to return an error
    // if no such survey was found.
});

________________________________

In server/controllers/survey.ts<https://github.com/Polar-Eclipse/survey-site/pull/36#discussion_r679347635>:

>              return next(err);
         }
-        res.render("index", { title: "EditSurvey", page: "editsurvey", surveyItem: survey });
+        getSurveyById(id, (err,survey) => {


You are making a find call on the database twice to get the same object. We do not want this to minimize database calls. I would suggest using getSurveyById only (and get rid of the Survey.find call above) and then checking if the userId is the same as the owner field of the survey object.

getSurveyById(id, (err, survey) => {
    if (err) {
        return next(err);
    }

    if (!userId.equals(survey.owner)) {
        return res.redirect("/account"); // redirect to the account page
        // OR you could also try sending out 401 Unauthorized error (more advanced)
    }

    // Now you can render the page here
});

________________________________

In server/controllers/survey.ts<https://github.com/Polar-Eclipse/survey-site/pull/36#discussion_r679352084>:

>              return next(err);
         }
-        res.redirect("/account");
+        Survey.findByIdAndRemove(id, {}, (err) => {


Same as above, you're requesting 2 database operations. What you want to use is this: Survey.findOneAndRemove<https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndRemove>.

Survey.findOneAndRemove({ owner: userId, _id: id }, (err) => {
    if (err) {
        return next(err);
    }

    res.redirect("/account");
    // This is done regardless of if the survey was actually found with the given id and owner id.
    // In business applications, you might want to do separate things depending on that.
    // In our case, I think it's fine to leave it like this.
});

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Polar-Eclipse/survey-site/pull/36#pullrequestreview-718353549>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AP7BHACF4ZWVY4GOJN76QHDT2GG6JANCNFSM5BFZB2VA>.

2021-07-30 01:05 UTC, JameeKim reviewed
Thanks for the work. One thing I want to mention is that `==` or `!=` in javascript is very... weird. You are better off using `===` or `!==` unless you exactly know what you're doing. I'll take care of it since it's a very tiny one. Again, thanks!

2021-07-30 02:55 UTC, JameeKim approved these changes, later dismissed

2021-07-30 03:04 UTC, JameeKim approved these changes

2021-07-30 03:06 UTC, merged